# Generated by Django 5.2.6 on 2025-09-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contatos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "logradouro",
                    models.CharField(
                        help_text="Logradouro do endereço", max_length=200
                    ),
                ),
                (
                    "numero",
                    models.CharField(help_text="Número do endereço", max_length=10),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        help_text="Complemento do endereço (opcional)",
                        max_length=100,
                    ),
                ),
                (
                    "bairro",
                    models.CharField(help_text="Bairro do endereço", max_length=100),
                ),
                (
                    "cidade",
                    models.CharField(help_text="Cidade do endereço", max_length=100),
                ),
                (
                    "estado",
                    models.CharField(help_text="Estado (UF) do endereço", max_length=2),
                ),
                ("cep", models.CharField(help_text="CEP do endereço", max_length=10)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to="Contatos.pessoa",
                    ),
                ),
            ],
        ),
    ]
